name: polyce_app
version: 0.0.1

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  analyzer: "^0.27.0"
  polymer: ">=1.0.0-rc.14"
  polyce: ">=0.1.0"
  polymer_elements: '>=1.0.0-rc.5'
  dart_to_js_script_rewriter: ">=0.1.0+4"
  web_components: "^0.12.0"
  browser: "^0.10.0"
  autonotify_observe: "^1.0.0+7"
  reflectable: ">=0.5.0"

transformers:
  - autonotify_observe
  - polymer:
      entry_points:
      - web/index.html
  - reflectable:
      entry_points:
      - web/index.dart
  - $dart2js:
      $include: '**/*.bootstrap.initialize.dart'
      minify: true
      commandLineOptions: ['--trust-type-annotations', '--trust-primitives', '--enable-experimental-mirrors']
  - dart_to_js_script_rewriter
